# Generated by Django 3.2.5 on 2021-07-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_phone'),
        ('customer', '0003_auto_20210713_1716'),
    ]

    operations = [
    ]
