# Generated by Django 3.2.5 on 2021-07-19 12:07

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210716_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 19, 12, 7, 49, 929198, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='avartar.jpg', upload_to='customer_pic'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
