# Generated by Django 3.2.5 on 2021-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
