# Generated by Django 3.2.5 on 2021-07-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='previous_balance',
        ),
    ]
