# Generated by Django 3.2.5 on 2021-07-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_balance_customer_previous_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='previous_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
