# Generated by Django 3.2.5 on 2021-07-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('product', '0002_auto_20210720_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('date', models.DateField()),
                ('purchase_no', models.IntegerField()),
                ('details', models.CharField(max_length=200, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'), serialize=False, to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
