# Generated by Django 3.2.5 on 2021-07-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210720_1641'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'), serialize=False, to='product.product'),
        ),
    ]
