# Generated by Django 3.2.5 on 2021-07-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210720_1641'),
        ('purchase', '0003_auto_20210720_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
