# Generated by Django 3.2.5 on 2021-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_rename_car_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
